### ISSUE TITLE
Implement "Burn" command

### ISSUE THREAD

**Issue by katabamia** [knh8205/K-Bot#6]
### Reason
The KNH焼き (Burning KNH) is one of identity of KNH.
To make bot more unique, why do not use this identity?
Twitter supporting `Twemoji` to show emojis, `🔥` will meaning `Burn` and `Fire`.
Its suitable to use in tweet.

### Command Example
`burn @exampleUser` or `burn exampleUser`

### Command Result
```
🔥🔥🔥🔥🔥🔥🔥🔥🔥 @exampleUser 🔥🔥🔥🔥🔥🔥🔥🔥🔥
```
Tweet random length of `🔥` emoji with specified username.

### Potential problems and solutions
Problem1. Command will used for spamming to any user.
Solution1. Set a limit to send message for each user.

Problem2. Tweet length will be over 140char.
Solution2. Generate string of `🔥` emoji between 1 to 30. (e.g.)

Problem3. The bot will send tweet to not F/F user.
Solution3. Only send tweet to F/F user.

### When close
When implemented `burn` feature or similar one.

**Comment by knh8205** [comment]
You better go to brain surgery? Let's bake brainstorm!
