### ISSUE TITLE
No sample of the configuration file(s) on repository.

### ISSUE THREAD

**Issue by KMR-zoar** [knh8205/K-Bot#7]
We can not run the clone system, because we can not check the sample of the configuration file(s).
Would you give us the sample of the configuration file(s)?

**Comment by knh8205** [comment]
PLEASE MAKE SURE THE DEVELOP BRANCH, IT WILL BE YOU NOTICED THAT YOU OVERLOOKED THE CONFIGURATION FILE.
THIS ISSUE WILL CLOSED NOW!!
